Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcudnn.so.5 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
Tensorflow_lim5000_proper_split_reweight_loss_batchC.py:101: RuntimeWarning: invalid value encountered in less
  a,b,c = (data1[i][2] < 8)*1,(data1[i][2] <= 15) & (data1[i][2] >= 8)*1,(data1[i][2] > 15)*1
Tensorflow_lim5000_proper_split_reweight_loss_batchC.py:101: RuntimeWarning: invalid value encountered in less_equal
  a,b,c = (data1[i][2] < 8)*1,(data1[i][2] <= 15) & (data1[i][2] >= 8)*1,(data1[i][2] > 15)*1
Tensorflow_lim5000_proper_split_reweight_loss_batchC.py:101: RuntimeWarning: invalid value encountered in greater_equal
  a,b,c = (data1[i][2] < 8)*1,(data1[i][2] <= 15) & (data1[i][2] >= 8)*1,(data1[i][2] > 15)*1
Tensorflow_lim5000_proper_split_reweight_loss_batchC.py:101: RuntimeWarning: invalid value encountered in greater
  a,b,c = (data1[i][2] < 8)*1,(data1[i][2] <= 15) & (data1[i][2] >= 8)*1,(data1[i][2] > 15)*1
Tensorflow_lim5000_proper_split_reweight_loss_batchC.py:131: RuntimeWarning: invalid value encountered in less
  a,b,c = (data1[i][2] < 8)*1,(data1[i][2] <= 15) & (data1[i][2] >= 8)*1,(data1[i][2] > 15)*1
Tensorflow_lim5000_proper_split_reweight_loss_batchC.py:131: RuntimeWarning: invalid value encountered in less_equal
  a,b,c = (data1[i][2] < 8)*1,(data1[i][2] <= 15) & (data1[i][2] >= 8)*1,(data1[i][2] > 15)*1
Tensorflow_lim5000_proper_split_reweight_loss_batchC.py:131: RuntimeWarning: invalid value encountered in greater_equal
  a,b,c = (data1[i][2] < 8)*1,(data1[i][2] <= 15) & (data1[i][2] >= 8)*1,(data1[i][2] > 15)*1
Tensorflow_lim5000_proper_split_reweight_loss_batchC.py:131: RuntimeWarning: invalid value encountered in greater
  a,b,c = (data1[i][2] < 8)*1,(data1[i][2] <= 15) & (data1[i][2] >= 8)*1,(data1[i][2] > 15)*1
Tensorflow_lim5000_proper_split_reweight_loss_batchC.py:149: RuntimeWarning: invalid value encountered in less
  a,b,c = (data1_t[i][2] < 8)*1,(data1_t[i][2] <= 15) & (data1_t[i][2] >= 8)*1,(data1_t[i][2] > 15)*1
Tensorflow_lim5000_proper_split_reweight_loss_batchC.py:149: RuntimeWarning: invalid value encountered in less_equal
  a,b,c = (data1_t[i][2] < 8)*1,(data1_t[i][2] <= 15) & (data1_t[i][2] >= 8)*1,(data1_t[i][2] > 15)*1
Tensorflow_lim5000_proper_split_reweight_loss_batchC.py:149: RuntimeWarning: invalid value encountered in greater_equal
  a,b,c = (data1_t[i][2] < 8)*1,(data1_t[i][2] <= 15) & (data1_t[i][2] >= 8)*1,(data1_t[i][2] > 15)*1
Tensorflow_lim5000_proper_split_reweight_loss_batchC.py:149: RuntimeWarning: invalid value encountered in greater
  a,b,c = (data1_t[i][2] < 8)*1,(data1_t[i][2] <= 15) & (data1_t[i][2] >= 8)*1,(data1_t[i][2] > 15)*1
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: Tesla K40t
major: 3 minor: 5 memoryClockRate (GHz) 0.745
pciBusID 0000:82:00.0
Total memory: 11.17GiB
Free memory: 11.10GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40t, pci bus id: 0000:82:00.0)
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 1711 get requests, put_count=1672 evicted_count=1000 eviction_rate=0.598086 and unsatisfied allocation rate=0.665693
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 100 to 110
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 1714 get requests, put_count=2009 evicted_count=1000 eviction_rate=0.49776 and unsatisfied allocation rate=0.424737
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:259] Raising pool_size_limit_ from 256 to 281
I tensorflow/core/common_runtime/gpu/pool_allocator.cc:247] PoolAllocator: After 2476369 get requests, put_count=2476354 evicted_count=1000 eviction_rate=0.000403819 and unsatisfied allocation rate=0.0004337
/app/tensorflow/1.0/lib/python2.7/site-packages/numpy/core/fromnumeric.py:2889: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/app/tensorflow/1.0/lib/python2.7/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "Tensorflow_lim5000_proper_split_reweight_loss_batchC.py", line 645, in <module>
    save_path = saver.save(sess,'model300_reweigh_loss_%s_%s.ckpt' %(epoch,int(100*np.mean(val_acc))))
ValueError: cannot convert float NaN to integer
